/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CowzfwdSDEY
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import { Link } from "react-router-dom";
import logo from "../../../public/logo.svg"
import head from "../../../public/head.png"
import cart from "../../../public/cart.png"
import CategoriesDropdown from "../CategoriesDropdown";
import { RiSearchLine } from "react-icons/ri";
import { FaRegHeart } from "react-icons/fa";



export function Menubar() {
  return (
    (<div
      className=" w-full   lg:h-14 md:h-12 bg-white ">


      {/* for large screen */}

      <Link href="#" className="lg:flex  hidden w-full items-center justify-between gap-[43px] text-[#323232]" prefetch={false}>
        {/* Left Section */}
        <div className="flex items-center gap-[43px]">
          <img src={logo} alt="" className="h-14 w-14 rounded-[2px]" />
          <CategoriesDropdown />
        </div>

        {/* Search Bar */}
       
          <div className="h-11  lg:mx-[10px] px-6 py-3 bg-[#efefef] hover:bg-[#dfdfdf] transition duration-300 rounded-full flex items-center justify-between flex-grow basis-0 leading-none">
            <p className="text-[16px] text-[#767676]">what are you looking for?</p>
            <RiSearchLine className="font-bold text-[20px] text-black" />
          </div>
       

        {/* Right Section */}
        <div className="flex items-center gap-2">
          <div className="flex gap-[6px] rounded-[6px] hover:bg-[#efefef] py-[10px] px-3 items-center text-[#323232] h-10 leading-none transition-colors duration-300">
            <img src={head} className="h-7 w-7" alt="" />
            <p className="leading-none font-semibold">log in</p>
          </div>

          <div className="flex items-center gap-[5px]">
            <p className="h-12 w-12 flex items-center justify-center rounded-[6px] hover:bg-[#efefef] transition-colors duration-300">
              <FaRegHeart className="h-5 w-5" />
            </p>
            <div className="h-12 w-12 flex items-center justify-center rounded-[6px] hover:bg-[#efefef] transition-colors duration-300">
              <img src={cart} alt="" className="h-14 w-14" />
            </div>
          </div>
        </div>
      </Link>









      <div className="flex gap-2 lg:hidden items-center">
        <Link href="#" className="flex w-full items-center justify-between gap-[43px] text-[#323232]" prefetch={false}>
          {/* Left Section */}
          <div className="flex items-center gap-[43px]">
            <img src={logo} alt="" className="h-12 w-12 rounded-[2px]" />

          </div>

          {/* Search Bar */}
          <div className="h-11 px-6 py-3 md:mx-[14px] bg-[#efefef] hidden md:flex rounded-full  items-center justify-between flex-grow basis-0 leading-none">
            <p className="text-[16px] text-[#767676]">what are you looking for?</p>
            <RiSearchLine className="font-bold text-[20px] text-black" />
          </div>

          {/* Right Section */}
          <div className="flex items-center gap-2">
            <div className="flex gap-[6px] rounded-[6px] hover:bg-[#efefef] py-[10px] px-3 items-center text-[#323232] h-10 leading-none transition-colors duration-300">
              <img src={head} className="h-7 w-7" alt="" />
              <p className="leading-none font-semibold hidden md:block">log in</p>
            </div>

            <div className="flex items-center gap-[5px]">
              <p className="h-12 w-12 flex items-center justify-center rounded-[6px] hover:bg-[#efefef] transition-colors duration-300">
                <FaRegHeart className="h-5 w-5" />
              </p>
              <div className="h-12 w-12 flex items-center justify-center rounded-[6px] hover:bg-[#efefef] transition-colors duration-300">
                <img src={cart} alt="" className="h-14 w-14" />
              </div>
            </div>
          </div>




        </Link>
        <Sheet >

          <SheetTrigger asChild>
            <Button variant="outline" size="icon" className="lg:hidden h-12 w-12 border-0 shadow-none">

              <MenuIcon className="h-6 w-6 " />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right" >
            <div className="grid w-[200px] p-4">
              <Link
                href="#"
                className="text-lg font-medium hover:underline underline-offset-4"
                prefetch={false}>
                Home
              </Link>
              <Link
                href="#"
                className="text-lg font-medium hover:underline underline-offset-4"
                prefetch={false}>
                About
              </Link>
              <Link
                href="#"
                className="text-lg font-medium hover:underline underline-offset-4"
                prefetch={false}>
                Services
              </Link>
              <Link
                href="#"
                className="text-lg font-medium hover:underline underline-offset-4"
                prefetch={false}>
                Portfolio
              </Link>
              <Link
                href="#"
                className="text-lg font-medium hover:underline underline-offset-4"
                prefetch={false}>
                Contact
              </Link>
            </div>
          </SheetContent>
        </Sheet>

      </div>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
